title: Pavia a Colori
email: paviaacolori@gmail.com
description: >-
  Vogliamo una città migliore
baseurl: ""
url: "http://paviaacolori.it"

theme: jekyll-theme-so-simple
logo: "/assets/images/logo.jpg"
plugins:
  - jekyll-feed

footer_links:
  - title: Facebook
    url: https://facebook.com/paviaacolori
    icon:  fab fa-facebook-square
  - title: Statuto
    url: /statuto.pdf
    icon: fas fa-book
