title: Pavia a Colori
email: paviaacolori@gmail.com
description: >-
  Vogliamo una città migliore
baseurl: "/"
url: "http://paviaacolori.it"

remote_theme: "mmistakes/so-simple-theme@3.2.0" 
logo: "/assets/images/logo.jpg"
plugins:
  - jekyll-feed

footer_links:
  - title: Facebook
    url: https://facebook.com/paviaacolori
    icon:  fab fa-facebook-square
  - title: Instagram
    url: https://www.instagram.com/paviaacolori/
    icon: fab fa-instagram
  - title: Statuto
    url: /statuto.pdf
    icon: fas fa-book  
